version: '3.7'

services:
  mysql: 
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: store
      MYSQL_PASSWORD: store

volumes:
  mysql-data: